services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: clapstech-api
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: clapstech-app
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped
